In [1]:
import numpy as np
import pandas as pd

In [2]:
data_preprocessed = pd.read_csv('df_preprocessed.csv')

pd.set_option('display.max_rows', 999)
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [3]:
targets = np.where(data_preprocessed["Absenteeism Time in Hours"] >
                   data_preprocessed["Absenteeism Time in Hours"].median(), 1, 0)

In [4]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed["Excessive Absenteeism"] = targets

In [6]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [7]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Daily Work Load Average',
                                            'Distance to Work', 'Day of the week'], axis=1)

In [8]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [10]:
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                     289   33               30          0         2     1  
1                     118   50               31          0         1     0  
2                     179   38               31          0         0     0  
3                     279   39               24          0         2     0  
4                     289   33               30          0         2     1

In [11]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [12]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.columns = columns
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std
    
    def fit(self, X, y=None):
        self.scaler = StandardScaler(copy=self.copy, with_mean=self.with_mean, with_std=self.with_std)
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled],axis=1)[init_col_order]

In [13]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month_Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [14]:
#columns_to_scale = ['Month_Value','Day of the week', 'Transportation Expense','Distance to Work',
#                   'Age', 'Daily Work Load Average', 'Body Mass Index','Children', 'Pets']

columns_to_ommit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_ommit]

In [15]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [16]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Anaconda\lib\site-packages\numpy\core\fromnumeric.py:3438: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


CustomScaler(columns=['Month_Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [17]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [18]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
5           0         0         0         1     0.182726   
6           0         0         0         1     0.182726   
7           0         0         0         1     0.182726   
8           0         0         1         0     0.182726   
9           0         0         0         1     0.182726   
10          1         0         0         0     0.182726   
11          1         0         0         0     0.182726   
12          1         0         0         0     0.182726   
13          1         0         0         0     0.182726   
14          0         0         0         1     0.182726   
15          1         0         0         0     0.182726   
16          0         0         0         1     0.182726   
17          0         0         1         0     0.182726   
18          1         0         0         0     0.182726   
19          0         0         0         1     0.468236   
20          1         0         0         0     0.468236   
21          1         0         0         0     0.468236   
22          1         0         0         0     0.468236   
23          0         0         0         1     0.468236   
24          0         0         1         0     0.468236   
25          0         0         0         1     0.468236   
26          0         0         0         1     0.468236   
27          0         0         0         1     0.468236   
28          0         0         1         0     0.468236   
29          0         0         0         1     0.468236   
30          0         0         1         0     0.468236   
31          0         0         1         0     0.468236   
32          0         0         0         1     0.468236   
33          0         0         1         0     0.468236   
34          0         0         0         1     0.468236   
35          0         0         0         1     0.468236   
36          0         0         0         1     0.468236   
37          1         0         0         0     0.468236   
38          0         0         0         1     0.468236   
39          0         0         0         1     0.468236   
40          0         0         0         1     0.753746   
41          0         0         0         1     0.753746   
42          0         0         0         1     0.753746   
43          0         0         1         0     0.753746   
44          0         0         0         1     0.753746   
45          0         0         0         1     0.753746   
46          0         0         0         1     0.753746   
47          0         0         0         1     0.753746   
48          0         0         0         1     0.753746   
49          1         0         0         0     0.753746   
50          0         0         0         0     0.753746   
51          0         0         0         0     0.753746   
52          0         0         0         1     0.753746   
53          0         0         0         1     0.753746   
54          0         0         0         0     0.753746   
55          0         0         0         0     0.753746   
56          0         0         1         0     0.753746   
57          0         0         0         1     0.753746   
58          0         0         0         0     0.753746   
59          0         0         0         1     0.753746   
60          0         0         0         1     0.753746   
61          0         0         0         1     0.753746   
62          0         0         0         1     1.039256   
63          0         0         0         1     1.039256   
64          0         0         0         0     1.039256   
65          0         0         0         1  

In [19]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Anaconda\lib\site-packages\numpy\core\fromnumeric.py:3438: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


CustomScaler(columns=['Month_Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [20]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [21]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
5           0         0         0         1     0.182726   
6           0         0         0         1     0.182726   
7           0         0         0         1     0.182726   
8           0         0         1         0     0.182726   
9           0         0         0         1     0.182726   
10          1         0         0         0     0.182726   
11          1         0         0         0     0.182726   
12          1         0         0         0     0.182726   
13          1         0         0         0     0.182726   
14          0         0         0         1     0.182726   
15          1         0         0         0     0.182726   
16          0         0         0         1     0.182726   
17          0         0         1         0     0.182726   
18          1         0         0         0     0.182726   
19          0         0         0         1     0.468236   
20          1         0         0         0     0.468236   
21          1         0         0         0     0.468236   
22          1         0         0         0     0.468236   
23          0         0         0         1     0.468236   
24          0         0         1         0     0.468236   
25          0         0         0         1     0.468236   
26          0         0         0         1     0.468236   
27          0         0         0         1     0.468236   
28          0         0         1         0     0.468236   
29          0         0         0         1     0.468236   
30          0         0         1         0     0.468236   
31          0         0         1         0     0.468236   
32          0         0         0         1     0.468236   
33          0         0         1         0     0.468236   
34          0         0         0         1     0.468236   
35          0         0         0         1     0.468236   
36          0         0         0         1     0.468236   
37          1         0         0         0     0.468236   
38          0         0         0         1     0.468236   
39          0         0         0         1     0.468236   
40          0         0         0         1     0.753746   
41          0         0         0         1     0.753746   
42          0         0         0         1     0.753746   
43          0         0         1         0     0.753746   
44          0         0         0         1     0.753746   
45          0         0         0         1     0.753746   
46          0         0         0         1     0.753746   
47          0         0         0         1     0.753746   
48          0         0         0         1     0.753746   
49          1         0         0         0     0.753746   
50          0         0         0         0     0.753746   
51          0         0         0         0     0.753746   
52          0         0         0         1     0.753746   
53          0         0         0         1     0.753746   
54          0         0         0         0     0.753746   
55          0         0         0         0     0.753746   
56          0         0         1         0     0.753746   
57          0         0         0         1     0.753746   
58          0         0         0         0     0.753746   
59          0         0         0         1     0.753746   
60          0         0         0         1     0.753746   
61          0         0         0         1     0.753746   
62          0         0         0         1     1.039256   
63          0         0         0         1     1.039256   
64          0         0         0         0     1.039256   
65          0         0         0         1  

In [22]:
scaled_inputs.shape

(700, 11)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20)

In [25]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [26]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


### Modeling

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
reg = LogisticRegression()

In [29]:
reg.fit(x_train,y_train)

LogisticRegression()

In [30]:
reg.score(x_train,y_train) #accuracy

0.7732142857142857

### Manual checking of the accuracy

In [31]:
model_outputs = reg.predict(x_train)

In [32]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.7732142857142857

### Creating a summary table with the coefficient and intercept

In [33]:
reg.intercept_

array([-1.6474549])

In [34]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [35]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month_Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [36]:
column_names = unscaled_inputs.columns.values

In [37]:
summary_table = pd.DataFrame(columns = ["Feature Name"], data = column_names)
summary_table["Coefficient"] = reg.coef_.transpose()

summary_table.index = summary_table.index + 1
summary_table.loc[0] = ["Intercept", reg.intercept_[0]]

summary_table = summary_table.sort_index()

summary_table

Feature Name  Coefficient
0                Intercept    -1.647455
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5              Month_Value     0.158930
6   Transportation Expense     0.605284
7                      Age    -0.169891
8          Body Mass Index     0.279811
9                Education    -0.210533
10                Children     0.348262
11                    Pets    -0.277396

In [38]:
summary_table["Odds_ratio"] = np.exp(summary_table.Coefficient)
summary_table.sort_values("Odds_ratio", ascending=False)

Feature Name  Coefficient  Odds_ratio
3                 Reason_3     3.115553   22.545903
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
4                 Reason_4     0.839001    2.314054
6   Transportation Expense     0.605284    1.831773
10                Children     0.348262    1.416604
8          Body Mass Index     0.279811    1.322880
5              Month_Value     0.158930    1.172256
7                      Age    -0.169891    0.843757
9                Education    -0.210533    0.810152
11                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

### Testing the model

In [39]:
reg.score(x_test, y_test)

0.75

In [40]:
reg.predict_proba(x_test) # index 1 = probability of model assigned of being 1

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [41]:
reg.predict_proba(x_test)[:,-1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

In [45]:
reg.predict_proba(x_test)[:,-1].shape

(140,)

In [ ]:
model.predicted_outputs().to_csv(‘Absenteeism_predictions.csv', index = False)
                                 
df_preprocessed.to_csv('Absenteeism_preprocessed.csv', index=False).

### Save the model

In [42]:
import pickle

In [43]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [44]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)